import { AtmosphereTag } from '@/types';

export interface WeatherCodeInfo {
  code: number;
  label: string;
  description: string;
  icon: string;
  dayIcon: string;
  nightIcon: string;
  primaryTag: AtmosphereTag;
  particleType: 'rain' | 'snow' | 'stars' | 'fog' | 'sun_dust' | 'storm' | 'aurora';
  particleDensity: number;
  isPrecipitation: boolean;
}

export const WEATHER_CODES: Record<number, WeatherCodeInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Cloudless and crystal clear sky',
    icon: 'Sun',
    dayIcon: 'Sun',
    nightIcon: 'Moon',
    primaryTag: 'clear',
    particleType: 'stars',
    particleDensity: 30,
    isPrecipitation: false,
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly clear with drifting light wisps',
    icon: 'SunMedium',
    dayIcon: 'SunMedium',
    nightIcon: 'MoonStar',
    primaryTag: 'clear',
    particleType: 'stars',
    particleDensity: 25,
    isPrecipitation: false,
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Scattered clouds gliding across the sky',
    icon: 'CloudSun',
    dayIcon: 'CloudSun',
    nightIcon: 'CloudMoon',
    primaryTag: 'cloudy',
    particleType: 'sun_dust',
    particleDensity: 20,
    isPrecipitation: false,
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'A dense, atmospheric blanket of clouds',
    icon: 'Cloud',
    dayIcon: 'Cloud',
    nightIcon: 'Cloud',
    primaryTag: 'cloudy',
    particleType: 'fog',
    particleDensity: 35,
    isPrecipitation: false,
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Ethereal mist drifting through the air',
    icon: 'CloudFog',
    dayIcon: 'CloudFog',
    nightIcon: 'CloudFog',
    primaryTag: 'fog',
    particleType: 'fog',
    particleDensity: 60,
    isPrecipitation: false,
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    description: 'Crisp freezing mist clinging to the world',
    icon: 'CloudFog',
    dayIcon: 'CloudFog',
    nightIcon: 'CloudFog',
    primaryTag: 'fog',
    particleType: 'fog',
    particleDensity: 65,
    isPrecipitation: false,
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'A gentle, soothing sprinkle of raindrops',
    icon: 'CloudDrizzle',
    dayIcon: 'CloudDrizzle',
    nightIcon: 'CloudDrizzle',
    primaryTag: 'drizzle',
    particleType: 'rain',
    particleDensity: 40,
    isPrecipitation: true,
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Steady fine drizzle weaving through the breeze',
    icon: 'CloudDrizzle',
    dayIcon: 'CloudDrizzle',
    nightIcon: 'CloudDrizzle',
    primaryTag: 'drizzle',
    particleType: 'rain',
    particleDensity: 55,
    isPrecipitation: true,
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Thick atmospheric drizzle filling the air',
    icon: 'CloudRain',
    dayIcon: 'CloudRain',
    nightIcon: 'CloudRain',
    primaryTag: 'rain',
    particleType: 'rain',
    particleDensity: 70,
    isPrecipitation: true,
  },
  56: {
    code: 56,
    label: 'Freezing Drizzle',
    description: 'Glacial chilled drizzle',
    icon: 'CloudSnow',
    dayIcon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 45,
    isPrecipitation: true,
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Heavy freezing mist coating everything in ice',
    icon: 'CloudSnow',
    dayIcon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 65,
    isPrecipitation: true,
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Soft rain tapping against the pavement',
    icon: 'CloudRain',
    dayIcon: 'CloudRain',
    nightIcon: 'CloudRain',
    primaryTag: 'rain',
    particleType: 'rain',
    particleDensity: 60,
    isPrecipitation: true,
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Consistent rhythmic rainfall',
    icon: 'CloudRain',
    dayIcon: 'CloudRain',
    nightIcon: 'CloudRain',
    primaryTag: 'rain',
    particleType: 'rain',
    particleDensity: 85,
    isPrecipitation: true,
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Torrential rain pouring with deep intensity',
    icon: 'CloudRainWind',
    dayIcon: 'CloudRainWind',
    nightIcon: 'CloudRainWind',
    primaryTag: 'heavy_rain',
    particleType: 'rain',
    particleDensity: 110,
    isPrecipitation: true,
  },
  66: {
    code: 66,
    label: 'Freezing Rain',
    description: 'Chilled crystal rain turning into ice upon landing',
    icon: 'CloudSnow',
    dayIcon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 60,
    isPrecipitation: true,
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Intense icy downpour',
    icon: 'CloudSnow',
    dayIcon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 90,
    isPrecipitation: true,
  },
  71: {
    code: 71,
    label: 'Slight Snow Fall',
    description: 'Gentle snowflakes drifting softly from above',
    icon: 'Snowflake',
    dayIcon: 'Snowflake',
    nightIcon: 'Snowflake',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 50,
    isPrecipitation: true,
  },
  73: {
    code: 73,
    label: 'Moderate Snow Fall',
    description: 'Serene blanket of descending white flakes',
    icon: 'Snowflake',
    dayIcon: 'Snowflake',
    nightIcon: 'Snowflake',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 75,
    isPrecipitation: true,
  },
  75: {
    code: 75,
    label: 'Heavy Snow Fall',
    description: 'A swirling winter blizzard embracing the city',
    icon: 'CloudSnow',
    dayIcon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 120,
    isPrecipitation: true,
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Crisp tiny frozen beads dropping softly',
    icon: 'Snowflake',
    dayIcon: 'Snowflake',
    nightIcon: 'Snowflake',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 40,
    isPrecipitation: true,
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    description: 'Passing rain showers with moments of glow',
    icon: 'CloudSunRain',
    dayIcon: 'CloudSunRain',
    nightIcon: 'CloudMoonRain',
    primaryTag: 'rain',
    particleType: 'rain',
    particleDensity: 65,
    isPrecipitation: true,
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Vibrant waves of passing rain',
    icon: 'CloudRain',
    dayIcon: 'CloudRain',
    nightIcon: 'CloudRain',
    primaryTag: 'rain',
    particleType: 'rain',
    particleDensity: 85,
    isPrecipitation: true,
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Sudden ferocious downpour and wind gusts',
    icon: 'CloudRainWind',
    dayIcon: 'CloudRainWind',
    nightIcon: 'CloudRainWind',
    primaryTag: 'heavy_rain',
    particleType: 'rain',
    particleDensity: 120,
    isPrecipitation: true,
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    description: 'Light flurries dancing across the air',
    icon: 'Snowflake',
    dayIcon: 'Snowflake',
    nightIcon: 'Snowflake',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 55,
    isPrecipitation: true,
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Vigorous swirling snow flurries',
    icon: 'CloudSnow',
    dayIcon: 'CloudSnow',
    nightIcon: 'CloudSnow',
    primaryTag: 'snow',
    particleType: 'snow',
    particleDensity: 100,
    isPrecipitation: true,
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Electric flashes and deep reverberating thunder',
    icon: 'CloudLightning',
    dayIcon: 'CloudLightning',
    nightIcon: 'CloudLightning',
    primaryTag: 'thunderstorm',
    particleType: 'storm',
    particleDensity: 95,
    isPrecipitation: true,
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Hail',
    description: 'Dramatic electrical storm carrying ice hail',
    icon: 'CloudLightning',
    dayIcon: 'CloudLightning',
    nightIcon: 'CloudLightning',
    primaryTag: 'thunderstorm',
    particleType: 'storm',
    particleDensity: 110,
    isPrecipitation: true,
  },
  99: {
    code: 99,
    label: 'Severe Thunderstorm',
    description: 'Furious lightning tempest sweeping through the sky',
    icon: 'CloudLightning',
    dayIcon: 'CloudLightning',
    nightIcon: 'CloudLightning',
    primaryTag: 'thunderstorm',
    particleType: 'storm',
    particleDensity: 130,
    isPrecipitation: true,
  },
};

export function getWeatherInfo(code: number): WeatherCodeInfo {
  return (
    WEATHER_CODES[code] || {
      code,
      label: 'Atmospheric',
      description: 'Dynamic atmospheric conditions',
      icon: 'Cloud',
      dayIcon: 'Cloud',
      nightIcon: 'Cloud',
      primaryTag: 'cloudy',
      particleType: 'stars',
      particleDensity: 30,
      isPrecipitation: false,
    }
  );
}
